### PR TITLE
Fix SHA256 and Rebuild for Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by kszucs** [comment]
Depends on https://github.com/ibis-project/ibis/pull/1544

**Comment by cpcloud** [comment]
@kszucs I don't think we need to depend on ibis-project/ibis#1544, since there are no code changes there that are required to support 3.7.

**Comment by kszucs** [comment]
@cpcloud I see, but ibis' tests might fail because of the dependencies (which We can test in that PR). If We can tolerate that, this PR is good to go of course.

**Comment by xmnlab** [comment]
Ibis removes support for python 2 ... should py2 be skipped in this PR?

**Comment by cpcloud** [comment]
Closing.

**Pull request closed without merging**
