### PR TITLE
Update omniscidb backend location

### PR DESCRIPTION
**Pull request by datapythonista**
This is required by of https://github.com/ibis-project/ibis/pull/2392

### CODE REVIEW

**Comment by jreback** [comment]
dont' we need to merge the ibis part first?

**Comment by datapythonista** [comment]
> dont' we need to merge the ibis part first?

I'm not sure. The Ibis part is ready, and its CI is red because of the feedstock: https://github.com/ibis-project/ibis/pull/2392 And here it's the other way round. I guess it doesn't make a difference which is merged first, as fas as both are merged more or less at the same time.

**Comment by jreback** [comment]
ok merging both

**Comment by tswast** [comment]
Seems like you need to cut a release after the move in https://github.com/ibis-project/ibis/pull/2392 in order for this feedstock build to pass. I'm tempted to revert this change in https://github.com/conda-forge/ibis-framework-feedstock/pull/48 to get a green build, but then I guess the ibis build itself will start failing?

**Pull request merged**
