### PR TITLE
chore: clear snapshots before install

### PR DESCRIPTION
**Pull request by gforsyth**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gforsyth** [comment]
Bit of a cludgy attempt to handle https://github.com/ibis-project/ibis/issues/9184 where certain test snapshot results are causing verification errors -- I don't think we lose anything by removing the expected snapshot results from the package.

**Comment by cpcloud** [comment]
Seems fine to remove them here.

**Comment by cpcloud** [comment]
Do we also need to somehow ignore the tests that would use them?

**Comment by cpcloud** [comment]
Or, if we're not running the tests at all then my question can be ignored!

**Comment by gforsyth** [comment]
yeah, no tests runs in the build here just because of the CI nightmare.  Ok, I'm going to try merging this and we'll see what happens

**Pull request merged**
