### PR TITLE
Update recipe for version 0.11.2

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
Probably need a feedstock rerender

**Comment by cpcloud** [comment]
@mariusvniekerk What does that mean?

**Comment by cpcloud** [comment]
@mariusvniekerk ah: https://conda-forge.github.io/docs/conda_smithy.html

**Comment by cpcloud** [comment]
@jakirkham @ocefpaf Any idea why conda is reporting conflicting MD5 sums for `fastavro`, or why there's conflicting metadata at all? Deleting the package cache seems to have no effect: https://circleci.com/gh/conda-forge/ibis-framework-feedstock/29

**Comment by cpcloud** [comment]
@mariusvniekerk Can you remove the smaller `fastavro-0.14.3-py27_0` package on anaconda.org? That would allow this recipe to build and then I can send out an ibis release announcement.

**Comment by cpcloud** [comment]
That package is here: https://anaconda.org/conda-forge/fastavro/files?version=0.14.3, and it's the one that's slightly smaller at 980.5 kB.

**Comment by mariusvniekerk** [comment]
i can rerender them with a new build number

**Comment by jakirkham** [comment]
I think what you are referring to is the two Linux 64-bit Python 2.7 ibis-framework 0.14.3 packages. Is that correct, @cpcloud? They seem to be the same size, but one had 0 downloads. Have labeled the package as `broken` (we are not in the habit of deleting packages these days). A screenshot of the change I made is shown below. That should resolve downloading this package on Linux in a Python 2.7 environment. FWIW this is due to upstream issue ( https://github.com/ContinuumIO/anaconda-issues/issues/1607 ).

As I will be out most of the weekend and into next week, I'm unlikely to be able to assist further should there be other issues. So would recommend following @mariusvniekerk's advice regarding bumping the build number if necessary (though it might not be necessary now). Could also ping other core members, but as FYI there will likely be low availability over the weekend and for those in the US low availability into the next week.

screen shot 2017-06-30 at 22 04 05

**Comment by cpcloud** [comment]
@wesm Can you have a look at this when you get a chance?

**Review by wesm — APPROVED** [review]
LGTM

**Pull request merged**
