### PR TITLE
CLN: Remove skeleton imports

### PR DESCRIPTION
**Pull request by cpcloud**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xmnlab** [comment]
@cpcloud it seems you need to update the sha256

**Comment by cpcloud** [comment]
I'm not sure why. I haven't changed the commit the tag points to

**Comment by xmnlab** [comment]
It seems it occurs frequently maybe some behavior of github

**Comment by cpcloud** [comment]
@xmnlab Good to go?

**Review by xmnlab — APPROVED** [review]

**Pull request merged**
