### PR TITLE
build: automate updates using the conda forge bot

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
@conda-forge-admin rerender

**Comment by cpcloud** [comment]
@conda-forge-admin rerender

**Comment by cpcloud** [comment]
@jreback this is ready to go

**Review by jreback — APPROVED** [review]

**Comment by cpcloud** [comment]
I can't merge it yet though :)

**Comment by jreback** [comment]
sure

failing checks ok?

**Comment by cpcloud** [comment]
@jreback fixed, will ping you on green

**Comment by jreback** [comment]
agtm

**Comment by cpcloud** [comment]
@jreback this is good to merge!

**Comment by cpcloud** [comment]
@jreback thoughts on this? can you merge it?

**Review by jreback — APPROVED** [review]

**Pull request merged**
