### PR TITLE
Bump pymapd to 0.24

### PR DESCRIPTION
**Pull request by jclay**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This PR updates the pymapd dependency to 0.24 as required by https://github.com/ibis-project/ibis/pull/2256.

### CODE REVIEW

**Comment by jclay** [comment]
@conda-forge-admin, please rerender

**Review by xmnlab — APPROVED** [review]
LGTM! thanks @jclay !

**Review by jreback — CHANGES_REQUESTED** [review]
let's pin to 0.23. if you want to do something on an experimental build ok, but we need to have a different set of packages. This changing in pymapd is causing lots of issues.

**Comment by jreback** [comment]
thanks but we r pinning to 0.23
to avoid breaking the world

**Pull request closed without merging**
