### PR TITLE
ENH: automate the recipe

### PR DESCRIPTION
**Pull request by cpcloud**
- ENH: turn on bot dep discovery
- MAINT: add cpcloud as maintainer

### CODE REVIEW

**Review by mariusvniekerk — APPROVED** [review]

**Review by datapythonista — APPROVED** [review]
lgtm

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by xmnlab** [comment]
Lgtm! I didn't know this bot, it looks very nice!

**Comment by cpcloud** [comment]
Unfortunately this is a no-go due to ibis having unconstrained an unconstrained sqlalchemy version

**Comment by cpcloud** [comment]
I will make sure to constrain sqlalchemy in the next release, or address the incompatibility in the next release.

**Pull request closed without merging**
