### PR TITLE
Update meta.yaml for 0.8 release

### PR DESCRIPTION
**Pull request by wesm**
This is a major release. Depends on conda-forge/impyla#4

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
So this guy failed because impyla is not in yet.  Best would be if you add some core member of the impyla / ibis team so that you can control some of these recipes yourself

**Comment by wesm** [comment]
@mariusvniekerk I'm a maintainer of impyla and this patch adds me as a maintainer to ibis-framework

**Comment by wesm** [comment]
I see, the impyla build failed. I'll make a patch

**Comment by wesm** [comment]
Did PyPI just change all their download URLs?

**Comment by mariusvniekerk** [comment]
I actually had some issues pushing a new release to pypi just now myself.  Weird

**Comment by mariusvniekerk** [comment]
urls that work seem similar to what is on [pypi.io](https://pypi.io/project/ibis-framework/#files).

**Comment by mariusvniekerk** [comment]
Seems the windows builds are failing with due to https://github.com/cloudera/ibis/issues/844

Going to merge since windows builds will only be working in 0.8.2

**Comment by wesm** [comment]
Thanks -- I will get a 0.8.2 out there with the Windows bug fix and make a new PR here

**Pull request merged**
